//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int IdUsuario { get; set; }
        public int NCuenta { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
